language: android
sudo: required
jdk: oraclejdk8
android:
components:
- platform-tools
- tools
- build-tools-25.0.1
- android-25
- extra-google-google_play_services
- extra-google-m2repository
- extra-android-m2repository
- sys-img-armeabi-v7a-android-25
before_install:
- chmod +x gradlew
script: ./gradlew assembleDebug
licenses:
- 'android-sdk-preview-license-52d11cd2'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'
