# This is a sample build configuration for Gradle.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: uber/android-build-environment:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - echo y | android update sdk --no-ui -a --filter platform-tools,android-24,build-tools-24.0.3,extra-android-support,extra-android-m2repository,play-services-analytics-9.4.0,firebase-crash-9.4.0,firebase-core-9.4.0 # Grab the Android Support Repo which isn't included in the container
          - ./gradlew --stacktrace --debug clean assembleDebug